baseURL = 'https://iocanel.com'
languageCode = 'en-us'
title = 'Ioannis Canellos'
theme = "github-style"

[pagination]
  pagerSize = 20

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Ioannis Canellos"
  description = "Software Engineer | Open Source Leader | Cloud-Native Expert"
  github = "iocanel"
  twitter = "iocanel"
  linkedin = "iocanel"
  youtube = "https://www.youtube.com/channel/UCDshZNBXJuU2aZYrmzZfkhg"
  email = "iocanel@gmail.com"
  url = "https://iocanel.com"
  avatar = "/images/avatar.png"
  headerIcon = "/images/avatar.png"
  location = "Greece"
  rss = false
  lastmod = true
  enableSearch = true
  custom_css = ["css/custom.css"]

[[params.nav]]
  title = "Blog"
  href = "/post/"
[[params.nav]]
  title = "Portfolio"
  href = "/portfolio/"
[[params.nav]]
  title = "Presentations"
  href = "/presentations/"
[[params.nav]]
  title = "About"
  href = "/about/"

[permalinks]
  post = '/:year/:month/:title/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = 'nord'
    tabWidth = 4

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
